### ISSUE TITLE
Test is Failing Under .NET Core

### ISSUE THREAD

**Issue by JasonBock** [JasonBock/Rocks#94]
When I run the tests, for some reason `Rocks.Tests.SerializationTests.RoundtripWithXml` is failing with the following information:
```
System.ArgumentException : The path is not of a legal form.
Parameter name: path
   at System.IO.Path.GetDirectoryName(String path)
   at System.Xml.Serialization.TempAssembly.LoadGeneratedAssembly(Type type, String defaultNamespace, XmlSerializerImplementation& contract)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at Rocks.Tests.SerializationTests.RoundtripWithXml() in M:\JasonBock\Personal\Code Projects\Rocks\Rocks.Tests\SerializationTests.cs:line 69
```

This only fails with the .NET Core runner, not the .NET Framework one.

**Comment by JasonBock** [comment]
Latest commit to master fixed this by getting rid of the test. I frankly don't have the patience to debug `XmlSerializer` and why it doesn't work the mocked type :).
